### ISSUE TITLE
Building in TeamCity

### ISSUE THREAD

**Issue by tofutim** [Azure/azure-mobile-apps-net-client#315]
Hi, not sure if anyone else has run into this, but I am trying to build in TeamCity 2017.1 w/ VS2017 and I am getting this error in Client:

```
Open in IDE
Table\MobileServiceTable.Generic.cs(367, 61): error CS1061: 'T[]' does not contain a definition for 'AsQueryable' and no extension method 'AsQueryable' accepting a first argument of type 'T[]' could be found (are you missing a using directive or an assembly reference?)
Table\Query\Linq\MobileServiceTableQuery.cs(113, 61): error CS0103: The name 'Queryable' does not exist in the current context
Table\Query\Linq\MobileServiceTableQuery.cs(148, 46): error CS0103: The name 'Queryable' does not exist in the current context
Table\Query\Linq\MobileServiceTableQuery.cs(173, 58): error CS0103: The name 'Queryable' does not exist in the current context
Table\Query\Linq\MobileServiceTableQuery.cs(196, 58): error CS0103: The name 'Queryable' does not exist in the current context
Table\Query\Linq\MobileServiceTableQuery.cs(219, 58): error CS0103: The name 'Queryable' does not exist in the current context
Table\Query\Linq\MobileServiceTableQuery.cs(242, 58): error CS0103: The name 'Queryable' does not exist in the current context
Table\Query\Linq\MobileServiceTableQuery.cs(256, 58): error CS0103: The name 'Queryable' does not exist in the current context
Table\Query\Linq\MobileServiceTableQuery.cs(270, 58): error CS0103: The name 'Queryable' does not exist in the current context
Table\Query\Linq\MobileServiceTableQueryTranslator.cs(144, 59): error CS0246: The type or namespace name 'Queryable' could not be found (are you missing a using directive or an assembly reference?)
Table\Sync\MobileServiceSyncTable.Generic.cs(145, 73): error CS1061: 'T[]' does not contain a definition for 'AsQueryable' and no extension method 'AsQueryable' accepting a first argument of type 'T[]' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by tofutim** [comment]
In case anyone else runs into this, the solution is that you cannot do the VS2017 build under the SYSTEM account, build agent has to be running some other (Admin) account. You can prove it to yourself by using psexec to log in as SYSTEM and try running msbuild. No matter what, it will fail with this issue. Start TeamCity agent with another account and it will work.
